version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: conexa-api
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: ${DB_NAME}
    volumes:
      - ./init-mongo.js:/docker-entrypoint-initdb.d/init-mongo.js:ro